#!/usr/bin/env bash
# Display nmbrs from 1 to 10 in list format.
# Display fizzbuzz when numbr=3 and 5.
# Display Fizz when the number is a multiple of 3.
# Displays Buzz when number is a 5 multiple.
# Otherwise , displays the nmuber.
for num in {1..100}
do
if ((num % 3 == 0 && num % 5 == 0))
then 
echo "FizzBuzz"
elif (( num % 3 ==0 ))
then
echo "Fizz"
elif (( num % 5 == 0))
then 
echo "Buzz"
else
echo "$num"
fi
done
