#!/usr/bin/env bash
#disply numbrs from 1 to 100 in list format
# display "FizzBuzz" when number is a mltiple of 3 and 5.
# display "Fizz" when nmbr is multiple of 3
# Display "Buzz" when numbr is a multiple of 5
# Else disply nmbr
for num in {1..100}
do
if (( num % 3 == 0 && num % 5 == 0 ))
then
echo "FizzBuzz"
elif (( num % 3 == 0 ))
then
echo "Fizz"
elif (( num % 5 == 0 ))
then
echo "Buzz"
else
echo "$num"
fi
done
