#!/usr/bin/env bash
# Displays nmbrs from 1 to 20 :
# bad luck from china for 4th rep
# bad luck from japan for 9th rep
# bad luck form Italy for 17th rep

count=1

while [ $count -le 20 ]
do 
echo "$count"
case $count in
"4") echo "bad luck from China";;
"9") echo "bad luck from Japan";;
"17") echo "bad luck from Italy";;
esac
(( count++ ))
done
