#!/usr/bin/env bash
#Displays time for 12hrs and 59min
# Displays from 0 to 12 hrs
# Displays from 1 to 59 mins
hour=0
while [ $hour -le 12 ]
do 
echo "Hour: $hour"
minute=1
while [ $minute -le 59 ]
do 
echo "$minute"
(( minute++ ))
done
(( hour++ ))
done
