#!/usr/bin/env bash
# Dispalys info about file 'school'.
if [ -e "school" ]
then
echo "school file exists"	
if [ -s "school" ]
then
echo "school file is not empty"
else
echo "School file is empty
fi
if [ -f "school" ]
then
echo "School is a regular file"
fi
else
echo "School file does not exist"
fi
